name: fantasy_novel
description: create a random fantasy world, a story plot, and one character agent
steps:
  - name: identity
    step_type: FILE_LOAD
    file: identity.txt
  - name: setup simulation
    step_type: DB_SIMULATION
  - name: setup world
    step_type: PROMPT_ENTITY
    entity_type: WORLD
    file: setup_entity_world.txt  
  - name: setup place
    step_type: PROMPT_ENTITY
    entity_type: PLACE
    file: setup_entity_place.txt
  - name: setup npc
    step_type: PROMPT_ENTITY
    entity_type: NPC
    file: setup_entity_npc.txt