name: fantasy_world
description: create a random fantasy world and an agent acting within it
steps:
  - name: save simulation instance
    step_type: save_simulation
    file: 
    results:
      - name: simulation_id
  - name: identity for the llm assistant
    step_type: load
    file: identity_writer.txt
    results:
      - name: identity
  - name: get style prompt
    step_type: load
    file: writing_style.txt
    results:
      - name: writing_style
  - name: create world
    step_type: prompt
    file: create_world.txt
    results:
      - name: world_name
      - name: world_summary
      - name: world_description
  - name: save world
    step_type: save_world
    file: 
    results:
      - name: world_id
  - name: create place
    step_type: prompt
    file: create_place.txt
    results:
      - name: place_name
      - name: place_summary
      - name: place_description
  - name: save place
    step_type: save_place
    file: 
    results:
      - name: place_id          
  - name: create npc
    step_type: prompt
    file: create_npc.txt
    results:
      - name: npc_name
      - name: npc_summary
      - name: npc_description
  - name: save npc
    step_type: save_npc
    file: 
    results:
      - name: npc_id
  - name: run world agent
    step_type: agent
    file: agent_world.yaml
    results:
  - name: run npc agent
    step_type: agent
    file: agent_npc.yaml